name: Execution Spec Tests Fill and Consume (Verkle genesis & conversion)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, kaustinen-with-shapella]
  workflow_dispatch:

env:
  EEST_USER: 'jsign'
  EEST_BRANCH: 'jsign-verkle-rebased-mainnet'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout go-ethereum
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.4"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.4

      - name: Build geth evm
        run: |
          go build -v ./cmd/evm
          mkdir -p ${{ github.workspace }}/bin
          mv evm ${{ github.workspace }}/bin/evm
          chmod +x ${{ github.workspace }}/bin/evm

      - name: Archive built evm
        uses: actions/upload-artifact@v4
        with:
          name: evm
          path: ${{ github.workspace }}/bin/evm

  fill-genesis:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Download geth evm
        uses: actions/download-artifact@v4
        with:
          name: evm
          path: ./bin

      - name: Make evm binary executable and add to PATH
        run: |
          chmod +x ./bin/evm
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Clone execution-spec-tests and fill genesis tests
        run: |
          git clone https://github.com/${{ env.EEST_USER }}/execution-spec-tests -b ${{ env.EEST_BRANCH }}
          cd execution-spec-tests
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -e ".[docs,lint,test]"
          solc-select use 0.8.24 --always-install
          fill --fork Verkle --output=../genesis-fixtures -v -m blockchain_test -k "not test_blockhash_insufficient_gas" -n auto
        shell: bash

      - name: Upload genesis fixtures
        uses: actions/upload-artifact@v4
        with:
          name: genesis-fixtures
          path: genesis-fixtures

  fill-conversion:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Download geth evm
        uses: actions/download-artifact@v4
        with:
          name: evm
          path: ./bin

      - name: Make evm binary executable and add to PATH
        run: |
          chmod +x ./bin/evm
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Clone execution-spec-tests and fill conversion tests
        run: |
          git clone https://github.com/${{ env.EEST_USER }}/execution-spec-tests -b ${{ env.EEST_BRANCH }}
          cd execution-spec-tests
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -e ".[docs,lint,test]"
          solc-select use 0.8.24 --always-install
          fill --fork EIP6800Transition --output=../conversion-fixtures -v -m blockchain_test -n auto
        shell: bash

      - name: Upload conversion fixtures
        uses: actions/upload-artifact@v4
        with:
          name: conversion-fixtures
          path: conversion-fixtures

  consume-genesis:
    runs-on: ubuntu-latest
    needs: fill-genesis
    steps:
      - name: Download geth evm
        uses: actions/download-artifact@v4
        with:
          name: evm
          path: ./bin

      - name: Make evm binary executable and add to PATH
        run: |
          chmod +x ./bin/evm
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Download genesis fixtures
        uses: actions/download-artifact@v4
        with:
          name: genesis-fixtures
          path: ./fixtures-genesis

      - name: Clone execution-spec-tests and consume genesis tests
        run: |
          git clone https://github.com/${{ env.EEST_USER }}/execution-spec-tests -b ${{ env.EEST_BRANCH }}
          cd execution-spec-tests
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -e ".[docs,lint,test]"
          solc-select use 0.8.24 --always-install
          consume direct --input=../fixtures-genesis -n auto
        shell: bash

  consume-conversion:
    runs-on: ubuntu-latest
    needs: fill-conversion
    steps:
      - name: Download geth evm
        uses: actions/download-artifact@v4
        with:
          name: evm
          path: ./bin

      - name: Make evm binary executable and add to PATH
        run: |
          chmod +x ./bin/evm
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Download conversion fixtures
        uses: actions/download-artifact@v4
        with:
          name: conversion-fixtures
          path: ./fixtures-conversion

      - name: Clone execution-spec-tests and consume conversion tests
        run: |
          git clone https://github.com/${{ env.EEST_USER }}/execution-spec-tests -b ${{ env.EEST_BRANCH }}
          cd execution-spec-tests
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -e ".[docs,lint,test]"
          solc-select use 0.8.24 --always-install
          consume direct --input=../fixtures-conversion -n auto
        shell: bash